global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'api-gateway'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'api-gateway:8060' ]

- job_name: 'course-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'course-service:8064' ]

- job_name: 'participant-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'participant-service:8065' ]

- job_name: 'instructor-service'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'instructor-service:8066' ]


# Jika menggunakan Node Exporter untuk host metrics
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
